services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cbt_web
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro
      - storage:/var/www/html/storage
    networks:
      - cbt_net
      - caddy_net

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.prod
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cbt_net

volumes:
  mysql_data:
  storage:

networks:
  cbt_net:
    driver: bridge
  caddy_net:
    external: true
